server:
    port: 8000
    error:
      include-message: always
      include-stacktrace: never
spring:
        datasource:
            url: jdbc:h2:mem:testdb
            username: sa
            password: password
            driverClassName: org.h2.Driver
            continue-on-error: false
        h2:
            console.enable: true
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            defer-datasource-initialization: true
